---
#- hosts: uat-webservers
#  roles:
#     - webserver

#- hosts: nginx
#  roles:
#     - nginx

#- hosts:  artifactory                                                                                                                                                                                                                                - hosts: artifactory
#  roles:
#     - artifactory

- hosts: db
  roles:
     - mysql