# [db]
# 172.31.44.66 ansible_ssh_user='ec2-user'

#[lb]
#172.31.17.163 ansible_ssh_user=ubuntu


#[webservers]
#172.31.27.44 ansible_ssh_user=ec2-user
#172.31.22.254 ansible_ssh_user=ec2-user

#[nginx]
#172.31.47.245 ansible_ssh_user='ec2-user'

[todo]
172.31.11.246 ansible_ssh_user='ec2-user'